In [236]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import category_encoders as ce
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

- [One hot encoding](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#One-hot-encoding)
- [Label encoding](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#Label-encoding)
- [Ordinal encoding](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#Ordinal-Encoding)
- [Binary encoding](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#Binary-Encoding)
- [Count encoding](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#Count-Encoding)
- [Target encoding (Mean encoding)](http://localhost:8888/notebooks/projects/machine_learning/Encode_categorical_data.ipynb#Target-Encoding-(Mean-Encoding))

In [237]:
df = pd.read_csv('DATA/Ames_NO_Missing_Data.csv')
df.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,3,2010,WD,Normal,189900

In [238]:
my_object_df = df.select_dtypes(include = 'object')
my_numeric_df = df.select_dtypes(exclude = 'object')
print(my_object_df.shape)

(2925, 39)

# One hot encoding
Кожна унікальна категорія перетворюється в бінарний вектор фіксованої довжини, де всі елементи рівні 0, за винятком одного, який вказує на належність до конкретної категорії. Цей метод дозволяє представити категоріальні дані у вигляді, зрозумілому для моделей.

In [239]:
df_object_dummies = pd.get_dummies(my_object_df, drop_first = True)
print(df_object_dummies.shape)
df_object_dummies

(2925, 212)

,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Street_Pave,Lot Shape_IR2,Lot Shape_IR3,Lot Shape_Reg,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,False,False,False,True,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False
2,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,False,False,False,False,True,False,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2921,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2922,False,False,False,False,True,False,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False
2923,False,False,False,False,True,False,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False
2924,False,False,False,False,True,False,True,False,False,True,...,False,False,False,False,True,False,False,False,True,False

In [240]:
enc = OneHotEncoder() 
encoder = ce.OneHotEncoder(cols=my_object_df.columns, return_df=True, use_cat_names=True)
one_hot_encoded = encoder.fit_transform(my_object_df)
print(one_hot_encoded.shape)
one_hot_encoded

(2925, 262)

,MS Zoning_RL,MS Zoning_RH,MS Zoning_FV,MS Zoning_RM,MS Zoning_C (all),MS Zoning_I (all),MS Zoning_A (agr),Street_Pave,Street_Grvl,Lot Shape_IR1,...,Sale Type_Oth,Sale Type_ConLw,Sale Type_CWD,Sale Type_VWD,Sale Condition_Normal,Sale Condition_Partial,Sale Condition_Family,Sale Condition_Abnorml,Sale Condition_Alloca,Sale Condition_AdjLand
0,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
2921,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
2922,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2923,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2924,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0

In [241]:
# in both sets existing
intersection = one_hot_encoded.columns.intersection(df_object_dummies.columns)
print(len(intersection))
intersection

212

Index(['MS Zoning_RL', 'MS Zoning_RH', 'MS Zoning_FV', 'MS Zoning_RM',
       'MS Zoning_C (all)', 'MS Zoning_I (all)', 'Street_Pave',
       'Lot Shape_Reg', 'Lot Shape_IR2', 'Lot Shape_IR3',
       ...
       'Sale Type_ConLD', 'Sale Type_Oth', 'Sale Type_ConLw', 'Sale Type_CWD',
       'Sale Type_VWD', 'Sale Condition_Normal', 'Sale Condition_Partial',
       'Sale Condition_Family', 'Sale Condition_Alloca',
       'Sale Condition_AdjLand'],
      dtype='object', length=212)

In [242]:
# in both sets besides intersection
symmetric_difference = one_hot_encoded.columns.symmetric_difference(df_object_dummies.columns)
print(len(symmetric_difference))
symmetric_difference

50

Index(['Bldg Type_1Fam', 'Bsmt Cond_Ex', 'Bsmt Cond_nan', 'Bsmt Exposure_Av',
       'Bsmt Exposure_nan', 'Bsmt Qual_Ex', 'Bsmt Qual_nan',
       'BsmtFin Type 1_ALQ', 'BsmtFin Type 1_nan', 'BsmtFin Type 2_ALQ',
       'BsmtFin Type 2_nan', 'Central Air_N', 'Condition 1_Artery',
       'Condition 2_Artery', 'Electrical_FuseA', 'Exter Cond_Ex',
       'Exter Qual_Ex', 'Exterior 1st_AsbShng', 'Exterior 2nd_AsbShng',
       'Fireplace Qu_Ex', 'Fireplace Qu_nan', 'Foundation_BrkTil',
       'Functional_Maj1', 'Garage Cond_Ex', 'Garage Cond_nan',
       'Garage Finish_Fin', 'Garage Finish_nan', 'Garage Qual_Ex',
       'Garage Qual_nan', 'Garage Type_2Types', 'Garage Type_nan',
       'Heating QC_Ex', 'Heating_Floor', 'House Style_1.5Fin',
       'Kitchen Qual_Ex', 'Land Contour_Bnk', 'Land Slope_Gtl',
       'Lot Config_Corner', 'Lot Shape_IR1', 'MS Zoning_A (agr)',
       'Mas Vnr Type_BrkCmn', 'Mas Vnr Type_nan', 'Neighborhood_Blmngtn',
       'Paved Drive_N', 'Roof Matl_CompShg', 'Roof Style_Flat',
       'Sale Condition_Abnorml', 'Sale Type_COD', 'Street_Grvl',
       'Utilities_AllPub'],
      dtype='object')

In [243]:
# only in one_hot_encoded set without data from intersection
difference = one_hot_encoded.columns.difference(df_object_dummies.columns)
print(len(difference))
difference

50

Index(['Bldg Type_1Fam', 'Bsmt Cond_Ex', 'Bsmt Cond_nan', 'Bsmt Exposure_Av',
       'Bsmt Exposure_nan', 'Bsmt Qual_Ex', 'Bsmt Qual_nan',
       'BsmtFin Type 1_ALQ', 'BsmtFin Type 1_nan', 'BsmtFin Type 2_ALQ',
       'BsmtFin Type 2_nan', 'Central Air_N', 'Condition 1_Artery',
       'Condition 2_Artery', 'Electrical_FuseA', 'Exter Cond_Ex',
       'Exter Qual_Ex', 'Exterior 1st_AsbShng', 'Exterior 2nd_AsbShng',
       'Fireplace Qu_Ex', 'Fireplace Qu_nan', 'Foundation_BrkTil',
       'Functional_Maj1', 'Garage Cond_Ex', 'Garage Cond_nan',
       'Garage Finish_Fin', 'Garage Finish_nan', 'Garage Qual_Ex',
       'Garage Qual_nan', 'Garage Type_2Types', 'Garage Type_nan',
       'Heating QC_Ex', 'Heating_Floor', 'House Style_1.5Fin',
       'Kitchen Qual_Ex', 'Land Contour_Bnk', 'Land Slope_Gtl',
       'Lot Config_Corner', 'Lot Shape_IR1', 'MS Zoning_A (agr)',
       'Mas Vnr Type_BrkCmn', 'Mas Vnr Type_nan', 'Neighborhood_Blmngtn',
       'Paved Drive_N', 'Roof Matl_CompShg', 'Roof Style_Flat',
       'Sale Condition_Abnorml', 'Sale Type_COD', 'Street_Grvl',
       'Utilities_AllPub'],
      dtype='object')

In [244]:
# only in df_object_dummies set without data from intersection
difference = df_object_dummies.columns.difference(one_hot_encoded.columns)
print(len(difference))
difference

0

Index([], dtype='object')

# Label encoding
Кожна унікальна категорія призначається унікальному цілочисельному значенню. Цей підхід використовується, коли категоріальні значення мають порядок або можна встановити певні взаємовідношення між ними.

In [245]:
from sklearn.preprocessing import LabelEncoder

In [246]:
def covert_to_number_categorical_numbers(column):
    return column.astype('category').cat.codes 

encoded = my_object_df.apply(covert_to_number_categorical_numbers, axis=0) 
encoded

,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,5,1,0,3,0,0,0,15,2,2,...,4,7,2,1,0,4,4,1,9,4
1,4,1,3,3,0,4,0,15,1,2,...,4,7,-1,1,2,4,4,2,9,4
2,5,1,0,3,0,0,0,15,2,2,...,2,7,-1,1,2,4,4,2,9,4
3,5,1,3,3,0,0,0,15,2,2,...,0,7,4,1,0,4,4,2,9,4
4,5,1,0,3,0,4,0,8,2,2,...,4,7,4,1,0,4,4,2,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,5,1,0,3,0,1,0,14,2,2,...,4,7,-1,5,2,4,4,2,9,4
2921,5,1,0,2,0,4,1,14,2,2,...,4,7,-1,1,2,4,4,2,9,4
2922,5,1,3,3,0,4,0,14,2,2,...,4,7,-1,-1,-1,-1,-1,2,9,4
2923,5,1,3,3,0,4,1,14,2,2,...,4,7,4,1,1,4,4,2,9,4
2924,5,1,3,3,0,4,1,14,2,2,...,4,7,4,1,0,4,4,2,9,4

In [247]:
label_encoder = LabelEncoder() 
encoded = my_object_df.apply(lambda column: label_encoder.fit_transform(column), axis=0) 
encoded

,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,5,1,0,3,0,0,0,15,2,2,...,4,7,2,1,0,4,4,1,9,4
1,4,1,3,3,0,4,0,15,1,2,...,4,7,5,1,2,4,4,2,9,4
2,5,1,0,3,0,0,0,15,2,2,...,2,7,5,1,2,4,4,2,9,4
3,5,1,3,3,0,0,0,15,2,2,...,0,7,4,1,0,4,4,2,9,4
4,5,1,0,3,0,4,0,8,2,2,...,4,7,4,1,0,4,4,2,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,5,1,0,3,0,1,0,14,2,2,...,4,7,5,5,2,4,4,2,9,4
2921,5,1,0,2,0,4,1,14,2,2,...,4,7,5,1,2,4,4,2,9,4
2922,5,1,3,3,0,4,0,14,2,2,...,4,7,5,6,3,5,5,2,9,4
2923,5,1,3,3,0,4,1,14,2,2,...,4,7,4,1,1,4,4,2,9,4
2924,5,1,3,3,0,4,1,14,2,2,...,4,7,4,1,0,4,4,2,9,4

In [248]:
def label_encoder(df, categorical_columns=None):
    df = df.copy()
    """Encode categorical values as integers (0,1,2,3...) with pandas.factorize. """
    # if categorical_colunms are not given than treat object as categorical features
    if not categorical_columns:
        categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    for col in categorical_columns:
        df[col], uniques = pd.factorize(df[col]) # change categorical feature to numerical values
    return df, categorical_columns
label_encoder(my_object_df)

(      MS Zoning  Street  Lot Shape  Land Contour  Utilities  Lot Config  \
 0             0       0          0             0          0           0
 1             1       0          1             0          0           1
 2             0       0          0             0          0           0
 3             0       0          1             0          0           0
 4             0       0          0             0          0           1
 ...         ...     ...        ...           ...        ...         ...
 2920          0       0          0             0          0           2
 2921          0       0          0             3          0           1
 2922          0       0          1             0          0           1
 2923          0       0          1             0          0           1
 2924          0       0          1             0          0           1

       Land Slope  Neighborhood  Condition 1  Condition 2  ...  Kitchen Qual  \
 0              0             0            0            0  ...             0
 1              0             0            1            0  ...             0
 2              0             0            0            0  ...             1
 3              0             0            0            0  ...             2
 4              0             1            0            0  ...             0
 ...          ...           ...          ...          ...  ...           ...
 2920           0            22            0            0  ...             0
 2921           1            22            0            0  ...             0
 2922           0            22            0            0  ...             0
 2923           1            22            0            0  ...             0
 2924           1            22            0            0  ...             0

       Functional  Fireplace Qu  Garage Type  Garage Finish  Garage Qual  \
 0              0             0            0              0            0
 1              0            -1            0              1            0
 2              0            -1            0              1            0
 3              0             1            0              0            0
 4              0             1            0              0            0
 ...          ...           ...          ...            ...          ...
 2920           0            -1            3              1            0
 2921           0            -1            0              1            0
 2922           0            -1           -1             -1           -1
 2923           0             1            0              2            0
 2924           0             1            0              0            0

       Garage Cond  Paved Drive  Sale Type  Sale Condition
 0               0            0          0               0
 1               0            1          0               0
 2               0            1          0               0
 3               0            1          0               0
 4               0            1          0               0
 ...           ...          ...        ...             ...
 2920            0            1          0               0
 2921            0            1          0               0
 2922           -1            1          0               0
 2923            0            1          0               0
 2924            0            1          0               0

 [2925 rows x 39 columns],
 ['MS Zoning',
  'Street',
  'Lot Shape',
  'Land Contour',
  'Utilities',
  'Lot Config',
  'Land Slope',
  'Neighborhood',
  'Condition 1',
  'Condition 2',
  'Bldg Type',
  'House Style',
  'Roof Style',
  'Roof Matl',
  'Exterior 1st',
  'Exterior 2nd',
  'Mas Vnr Type',
  'Exter Qual',
  'Exter Cond',
  'Foundation',
  'Bsmt Qual',
  'Bsmt Cond',
  'Bsmt Exposure',
  'BsmtFin Type 1',
  'BsmtFin Type 2',
  'Heating',
  'Heating QC',
  'Central Air',
  'Electrical',
  'Kitchen Qual',
  'Functional',
  'Fireplace Qu',
  'Garage Type',
  'Garage Finish',
  'Garage Qual',
  'Garage Cond',
  'Paved Drive',
  'Sale Type',
  'Sale Condition'])

# Ordinal Encoding
Схожий на Label Encoding, але дозволяє вказати порядок між категоріями. Наприклад, якщо категорії мають визначений порядок, такий як "низький", "середній", "високий", цей порядок враховується при присвоєнні цілочисельних значень.

In [249]:
sizes = ['small', 'medium', 'large']

# Encode colors as incremental integers 
encoded_sizes = np.arange(len(sizes))

print(encoded_sizes)


encoder = OrdinalEncoder()

# reshape to 2D array
sizes_reshaped = np.array(sizes).reshape(-1,1)

encoded = encoder.fit_transform(sizes_reshaped) 

print(encoded)

[0 1 2]
[[2.]
 [1.]
 [0.]]

In [250]:
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_
enc.transform([['Female', 3], ['Male', 1]])

array([[0., 2.],
       [1., 0.]])

In [251]:
encoder = OrdinalEncoder()
encoder.fit(my_object_df)
print('Categories: ', encoder.categories_)
encoded = encoder.transform(my_object_df)
print(encoded.shape)
encoded

Categories:  [array(['A (agr)', 'C (all)', 'FV', 'I (all)', 'RH', 'RL', 'RM'],
      dtype=object), array(['Grvl', 'Pave'], dtype=object), array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object), array(['Bnk', 'HLS', 'Low', 'Lvl'], dtype=object), array(['AllPub', 'NoSeWa', 'NoSewr'], dtype=object), array(['Corner', 'CulDSac', 'FR2', 'FR3', 'Inside'], dtype=object), array(['Gtl', 'Mod', 'Sev'], dtype=object), array(['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr',
       'Crawfor', 'Edwards', 'Gilbert', 'Greens', 'GrnHill', 'IDOTRR',
       'Landmrk', 'MeadowV', 'Mitchel', 'NAmes', 'NPkVill', 'NWAmes',
       'NoRidge', 'NridgHt', 'OldTown', 'SWISU', 'Sawyer', 'SawyerW',
       'Somerst', 'StoneBr', 'Timber', 'Veenker'], dtype=object), array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNe',
       'RRNn'], dtype=object), array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNn'],
      dtype=object), array(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE'], dtype=object), array(['1.5Fin', '1.5Unf', '1Story', '2.5Fin', '2.5Unf', '2Story',
       'SFoyer', 'SLvl'], dtype=object), array(['Flat', 'Gable', 'Gambrel', 'Hip', 'Mansard', 'Shed'], dtype=object), array(['CompShg', 'Membran', 'Metal', 'Roll', 'Tar&Grv', 'WdShake',
       'WdShngl'], dtype=object), array(['AsbShng', 'AsphShn', 'BrkComm', 'BrkFace', 'CBlock', 'CemntBd',
       'HdBoard', 'ImStucc', 'MetalSd', 'Plywood', 'PreCast', 'Stone',
       'Stucco', 'VinylSd', 'Wd Sdng', 'WdShing'], dtype=object), array(['AsbShng', 'AsphShn', 'Brk Cmn', 'BrkFace', 'CBlock', 'CmentBd',
       'HdBoard', 'ImStucc', 'MetalSd', 'Other', 'Plywood', 'PreCast',
       'Stone', 'Stucco', 'VinylSd', 'Wd Sdng', 'Wd Shng'], dtype=object), array(['BrkCmn', 'BrkFace', 'CBlock', 'Stone', nan], dtype=object), array(['Ex', 'Fa', 'Gd', 'TA'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object), array(['BrkTil', 'CBlock', 'PConc', 'Slab', 'Stone', 'Wood'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['Av', 'Gd', 'Mn', 'No', nan], dtype=object), array(['ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf', nan], dtype=object), array(['ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf', nan], dtype=object), array(['Floor', 'GasA', 'GasW', 'Grav', 'OthW', 'Wall'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object), array(['N', 'Y'], dtype=object), array(['FuseA', 'FuseF', 'FuseP', 'Mix', 'SBrkr'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object), array(['Maj1', 'Maj2', 'Min1', 'Min2', 'Mod', 'Sal', 'Sev', 'Typ'],
      dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd', nan],
      dtype=object), array(['Fin', 'RFn', 'Unf', nan], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['N', 'P', 'Y'], dtype=object), array(['COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth',
       'VWD', 'WD '], dtype=object), array(['Abnorml', 'AdjLand', 'Alloca', 'Family', 'Normal', 'Partial'],
      dtype=object)]
(2925, 39)

array([[5., 1., 0., ..., 1., 9., 4.],
       [4., 1., 3., ..., 2., 9., 4.],
       [5., 1., 0., ..., 2., 9., 4.],
       ...,
       [5., 1., 3., ..., 2., 9., 4.],
       [5., 1., 3., ..., 2., 9., 4.],
       [5., 1., 3., ..., 2., 9., 4.]])

In [252]:
encoder.inverse_transform(encoded)

array([['RL', 'Pave', 'IR1', ..., 'P', 'WD ', 'Normal'],
       ['RH', 'Pave', 'Reg', ..., 'Y', 'WD ', 'Normal'],
       ['RL', 'Pave', 'IR1', ..., 'Y', 'WD ', 'Normal'],
       ...,
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD ', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD ', 'Normal'],
       ['RL', 'Pave', 'Reg', ..., 'Y', 'WD ', 'Normal']], dtype=object)

# Binary Encoding
Категорії перетворюються в бінарний код, і кожна категорія представлена як комбінація бітів. Це дозволяє зменшити кількість стовпчиків у порівнянні з One-Hot Encoding, зберігаючи деяку інформацію про взаємовідношення між категоріями.

In [253]:
encoder = ce.BinaryEncoder(cols = my_object_df.columns , return_df = True)
encoded = encoder.fit_transform(my_object_df)
print(encoded.shape)
encoded

(2925, 123)

,MS Zoning_0,MS Zoning_1,MS Zoning_2,Street_0,Street_1,Lot Shape_0,Lot Shape_1,Lot Shape_2,Land Contour_0,Land Contour_1,...,Garage Cond_2,Paved Drive_0,Paved Drive_1,Sale Type_0,Sale Type_1,Sale Type_2,Sale Type_3,Sale Condition_0,Sale Condition_1,Sale Condition_2
0,0,0,1,0,1,0,0,1,0,0,...,1,0,1,0,0,0,1,0,0,1
1,0,1,0,0,1,0,1,0,0,0,...,1,1,0,0,0,0,1,0,0,1
2,0,0,1,0,1,0,0,1,0,0,...,1,1,0,0,0,0,1,0,0,1
3,0,0,1,0,1,0,1,0,0,0,...,1,1,0,0,0,0,1,0,0,1
4,0,0,1,0,1,0,0,1,0,0,...,1,1,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,0,0,1,0,1,0,0,1,0,0,...,1,1,0,0,0,0,1,0,0,1
2921,0,0,1,0,1,0,0,1,1,0,...,1,1,0,0,0,0,1,0,0,1
2922,0,0,1,0,1,0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,1
2923,0,0,1,0,1,0,1,0,0,0,...,1,1,0,0,0,0,1,0,0,1
2924,0,0,1,0,1,0,1,0,0,0,...,1,1,0,0,0,0,1,0,0,1

In [254]:
# in both sets existing
intersection = one_hot_encoded.columns.intersection(encoder.get_feature_names_out())
print(len(intersection))
intersection

0

Index([], dtype='object')

In [255]:
# in both sets without intersection data
symmetric_difference = one_hot_encoded.columns.symmetric_difference(encoder.get_feature_names_out())
print(len(symmetric_difference))
symmetric_difference

385

Index(['Bldg Type_0', 'Bldg Type_1', 'Bldg Type_1Fam', 'Bldg Type_2',
       'Bldg Type_2fmCon', 'Bldg Type_Duplex', 'Bldg Type_Twnhs',
       'Bldg Type_TwnhsE', 'Bsmt Cond_0', 'Bsmt Cond_1',
       ...
       'Sale Type_WD ', 'Street_0', 'Street_1', 'Street_Grvl', 'Street_Pave',
       'Utilities_0', 'Utilities_1', 'Utilities_AllPub', 'Utilities_NoSeWa',
       'Utilities_NoSewr'],
      dtype='object', length=385)

In [256]:
# only in one_hot_encoded without intersection data
difference = one_hot_encoded.columns.difference(encoder.get_feature_names_out())
print(len(difference))
difference

262

Index(['Bldg Type_1Fam', 'Bldg Type_2fmCon', 'Bldg Type_Duplex',
       'Bldg Type_Twnhs', 'Bldg Type_TwnhsE', 'Bsmt Cond_Ex', 'Bsmt Cond_Fa',
       'Bsmt Cond_Gd', 'Bsmt Cond_Po', 'Bsmt Cond_TA',
       ...
       'Sale Type_ConLw', 'Sale Type_New', 'Sale Type_Oth', 'Sale Type_VWD',
       'Sale Type_WD ', 'Street_Grvl', 'Street_Pave', 'Utilities_AllPub',
       'Utilities_NoSeWa', 'Utilities_NoSewr'],
      dtype='object', length=262)

In [257]:
# only in 1st set without intersection data
difference = set(encoder.get_feature_names_out()).difference(one_hot_encoded.columns)
print(len(difference))
difference

123

{'Bldg Type_0',
 'Bldg Type_1',
 'Bldg Type_2',
 'Bsmt Cond_0',
 'Bsmt Cond_1',
 'Bsmt Cond_2',
 'Bsmt Exposure_0',
 'Bsmt Exposure_1',
 'Bsmt Exposure_2',
 'Bsmt Qual_0',
 'Bsmt Qual_1',
 'Bsmt Qual_2',
 'BsmtFin Type 1_0',
 'BsmtFin Type 1_1',
 'BsmtFin Type 1_2',
 'BsmtFin Type 2_0',
 'BsmtFin Type 2_1',
 'BsmtFin Type 2_2',
 'Central Air_0',
 'Central Air_1',
 'Condition 1_0',
 'Condition 1_1',
 'Condition 1_2',
 'Condition 1_3',
 'Condition 2_0',
 'Condition 2_1',
 'Condition 2_2',
 'Condition 2_3',
 'Electrical_0',
 'Electrical_1',
 'Electrical_2',
 'Exter Cond_0',
 'Exter Cond_1',
 'Exter Cond_2',
 'Exter Qual_0',
 'Exter Qual_1',
 'Exter Qual_2',
 'Exterior 1st_0',
 'Exterior 1st_1',
 'Exterior 1st_2',
 'Exterior 1st_3',
 'Exterior 1st_4',
 'Exterior 2nd_0',
 'Exterior 2nd_1',
 'Exterior 2nd_2',
 'Exterior 2nd_3',
 'Exterior 2nd_4',
 'Fireplace Qu_0',
 'Fireplace Qu_1',
 'Fireplace Qu_2',
 'Foundation_0',
 'Foundation_1',
 'Foundation_2',
 'Functional_0',
 'Functional_1',
 'Functional_2',
 'Functional_3',
 'Garage Cond_0',
 'Garage Cond_1',
 'Garage Cond_2',
 'Garage Finish_0',
 'Garage Finish_1',
 'Garage Finish_2',
 'Garage Qual_0',
 'Garage Qual_1',
 'Garage Qual_2',
 'Garage Type_0',
 'Garage Type_1',
 'Garage Type_2',
 'Heating QC_0',
 'Heating QC_1',
 'Heating QC_2',
 'Heating_0',
 'Heating_1',
 'Heating_2',
 'House Style_0',
 'House Style_1',
 'House Style_2',
 'House Style_3',
 'Kitchen Qual_0',
 'Kitchen Qual_1',
 'Kitchen Qual_2',
 'Land Contour_0',
 'Land Contour_1',
 'Land Contour_2',
 'Land Slope_0',
 'Land Slope_1',
 'Lot Config_0',
 'Lot Config_1',
 'Lot Config_2',
 'Lot Shape_0',
 'Lot Shape_1',
 'Lot Shape_2',
 'MS Zoning_0',
 'MS Zoning_1',
 'MS Zoning_2',
 'Mas Vnr Type_0',
 'Mas Vnr Type_1',
 'Mas Vnr Type_2',
 'Neighborhood_0',
 'Neighborhood_1',
 'Neighborhood_2',
 'Neighborhood_3',
 'Neighborhood_4',
 'Paved Drive_0',
 'Paved Drive_1',
 'Roof Matl_0',
 'Roof Matl_1',
 'Roof Matl_2',
 'Roof Style_0',
 'Roof Style_1',
 'Roof Style_2',
 'Sale Condition_0',
 'Sale Condition_1',
 'Sale Condition_2',
 'Sale Type_0',
 'Sale Type_1',
 'Sale Type_2',
 'Sale Type_3',
 'Street_0',
 'Street_1',
 'Utilities_0',
 'Utilities_1'}

# Count Encoding
Кожна категорія замінюється її частотою зустрічання в даних. Цей підхід може бути ефективним, коли важливо враховувати частоту кожної категорії.

In [258]:
count_enc = ce.CountEncoder()
count_encoded = count_enc.fit_transform(my_object_df)

count_encoded

,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,2269,2913,977,2631,2922,510,2784,443,2519,2896,...,1494,2723,741,1729,724,2611,2661,62,2534,2412
1,27,2913,1857,2631,2922,2136,2784,443,163,2896,...,1494,2723,1420,1729,1231,2611,2661,2647,2534,2412
2,2269,2913,977,2631,2922,510,2784,443,2519,2896,...,1158,2723,1420,1729,1231,2611,2661,2647,2534,2412
3,2269,2913,1857,2631,2922,510,2784,443,2519,2896,...,202,2723,600,1729,724,2611,2661,2647,2534,2412
4,2269,2913,977,2631,2922,2136,2784,165,2519,2896,...,1494,2723,600,1729,724,2611,2661,2647,2534,2412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,2269,2913,977,2631,2922,180,2784,114,2519,2896,...,1494,2723,1420,781,1231,2611,2661,2647,2534,2412
2921,2269,2913,977,60,2922,2136,125,114,2519,2896,...,1494,2723,1420,1729,1231,2611,2661,2647,2534,2412
2922,2269,2913,1857,2631,2922,2136,2784,114,2519,2896,...,1494,2723,1420,157,158,158,158,2647,2534,2412
2923,2269,2913,1857,2631,2922,2136,125,114,2519,2896,...,1494,2723,600,1729,812,2611,2661,2647,2534,2412
2924,2269,2913,1857,2631,2922,2136,125,114,2519,2896,...,1494,2723,600,1729,724,2611,2661,2647,2534,2412

In [259]:
count_encoded = pd.DataFrame()
for column in my_object_df.columns:
    count_encoded[column] = my_object_df.groupby([column])['Sale Type'].transform('count')
count_encoded

,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,2269,2913,977,2631,2922,510,2784,443,2519,2896,...,1494,2723,741.0,1729.0,724.0,2611.0,2661.0,62,2534,2412
1,27,2913,1857,2631,2922,2136,2784,443,163,2896,...,1494,2723,NaN,1729.0,1231.0,2611.0,2661.0,2647,2534,2412
2,2269,2913,977,2631,2922,510,2784,443,2519,2896,...,1158,2723,NaN,1729.0,1231.0,2611.0,2661.0,2647,2534,2412
3,2269,2913,1857,2631,2922,510,2784,443,2519,2896,...,202,2723,600.0,1729.0,724.0,2611.0,2661.0,2647,2534,2412
4,2269,2913,977,2631,2922,2136,2784,165,2519,2896,...,1494,2723,600.0,1729.0,724.0,2611.0,2661.0,2647,2534,2412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,2269,2913,977,2631,2922,180,2784,114,2519,2896,...,1494,2723,NaN,781.0,1231.0,2611.0,2661.0,2647,2534,2412
2921,2269,2913,977,60,2922,2136,125,114,2519,2896,...,1494,2723,NaN,1729.0,1231.0,2611.0,2661.0,2647,2534,2412
2922,2269,2913,1857,2631,2922,2136,2784,114,2519,2896,...,1494,2723,NaN,NaN,NaN,NaN,NaN,2647,2534,2412
2923,2269,2913,1857,2631,2922,2136,125,114,2519,2896,...,1494,2723,600.0,1729.0,812.0,2611.0,2661.0,2647,2534,2412
2924,2269,2913,1857,2631,2922,2136,125,114,2519,2896,...,1494,2723,600.0,1729.0,724.0,2611.0,2661.0,2647,2534,2412

# Target Encoding (Mean Encoding)
Кожна категорія замінюється середнім значенням цільової змінної для цієї категорії. Це особливо корисно, коли цільова змінна є числовою.

In [260]:
data=pd.DataFrame({'class':['A,','B','C','B','C','A','A','A'],'Marks':[50,30,70,80,45,97,80,68]})
#Create target encoding object
encoder=ce.TargetEncoder(cols='class') 
encoded = encoder.fit_transform(data['class'], data['Marks'])
encoded

       class
0  63.048373
1  63.581489
2  63.936117
3  63.581489
4  63.936117
5  67.574421
6  67.574421
7  67.574421